/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface WaitlistEntry {
    preferredStartDate: string;
    homeType: HomeType;
    city: string;
    name: string;
    elderly: bigint;
    email: string;
    children: bigint;
    squareFootage: bigint;
    timestamp: Time;
    adults: bigint;
    phone: string;
}
export enum HomeType {
    PG = "PG",
    OneBHK = "OneBHK",
    TwoBHK = "TwoBHK",
    FourBHKPlus = "FourBHKPlus",
    ThreeBHK = "ThreeBHK"
}
export interface backendInterface {
    addCalculatorQuery(homeType: HomeType, squareFootage: bigint, adults: bigint, children: bigint, elderly: bigint, calculatedPrice: bigint, recommendedHours: bigint): Promise<void>;
    addWaitlistEntry(name: string, phone: string, email: string, city: string, homeType: HomeType, squareFootage: bigint, adults: bigint, children: bigint, elderly: bigint, preferredStartDate: string): Promise<void>;
    getAllWaitlistEntries(): Promise<Array<WaitlistEntry>>;
    getWaitlistCount(): Promise<bigint>;
}
import type { HomeType as _HomeType, Time as _Time, WaitlistEntry as _WaitlistEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCalculatorQuery(arg0: HomeType, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalculatorQuery(to_candid_HomeType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalculatorQuery(to_candid_HomeType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addWaitlistEntry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: HomeType, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWaitlistEntry(arg0, arg1, arg2, arg3, to_candid_HomeType_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWaitlistEntry(arg0, arg1, arg2, arg3, to_candid_HomeType_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async getAllWaitlistEntries(): Promise<Array<WaitlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWaitlistEntries();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWaitlistEntries();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaitlistCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitlistCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitlistCount();
            return result;
        }
    }
}
function from_candid_HomeType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomeType): HomeType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_WaitlistEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaitlistEntry): WaitlistEntry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredStartDate: string;
    homeType: _HomeType;
    city: string;
    name: string;
    elderly: bigint;
    email: string;
    children: bigint;
    squareFootage: bigint;
    timestamp: _Time;
    adults: bigint;
    phone: string;
}): {
    preferredStartDate: string;
    homeType: HomeType;
    city: string;
    name: string;
    elderly: bigint;
    email: string;
    children: bigint;
    squareFootage: bigint;
    timestamp: Time;
    adults: bigint;
    phone: string;
} {
    return {
        preferredStartDate: value.preferredStartDate,
        homeType: from_candid_HomeType_n6(_uploadFile, _downloadFile, value.homeType),
        city: value.city,
        name: value.name,
        elderly: value.elderly,
        email: value.email,
        children: value.children,
        squareFootage: value.squareFootage,
        timestamp: value.timestamp,
        adults: value.adults,
        phone: value.phone
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PG: null;
} | {
    OneBHK: null;
} | {
    TwoBHK: null;
} | {
    FourBHKPlus: null;
} | {
    ThreeBHK: null;
}): HomeType {
    return "PG" in value ? HomeType.PG : "OneBHK" in value ? HomeType.OneBHK : "TwoBHK" in value ? HomeType.TwoBHK : "FourBHKPlus" in value ? HomeType.FourBHKPlus : "ThreeBHK" in value ? HomeType.ThreeBHK : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WaitlistEntry>): Array<WaitlistEntry> {
    return value.map((x)=>from_candid_WaitlistEntry_n4(_uploadFile, _downloadFile, x));
}
function to_candid_HomeType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomeType): _HomeType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomeType): {
    PG: null;
} | {
    OneBHK: null;
} | {
    TwoBHK: null;
} | {
    FourBHKPlus: null;
} | {
    ThreeBHK: null;
} {
    return value == HomeType.PG ? {
        PG: null
    } : value == HomeType.OneBHK ? {
        OneBHK: null
    } : value == HomeType.TwoBHK ? {
        TwoBHK: null
    } : value == HomeType.FourBHKPlus ? {
        FourBHKPlus: null
    } : value == HomeType.ThreeBHK ? {
        ThreeBHK: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
